# A Replication of BLP(1995)
##### Last update: Dec. 2023

### This file replicates the following results in BLP(1995):

* Table I: Descriptive Statistics
* Table III: Results with Logit Demand and Marginal Cost Pricing
* Table IV: Esimated Parameters of the Demand and Pricing Equations (column 3)
* Table VI: A Sample of Estimated Own- and Cross-Price Semi-Elasticities

### Content:

1. [The Model](#1.-The-Model)
1. [Estimation Procedure](#2.-Estimation-Procedure)
1. [Define Functions](#3.-Define-Functions)
1. [Replications](#4.-Replications)
1. [Citations](#Citations)


## 1. The Model ##

### Demand Side:
Suppose there are $T$ markets (each market is a year), and $J_t$ products in each market $t$.

For each consumer $i$, his utility for purchasing product $j$ in market $t$ is given by:

$$
u_{ijt} = \alpha log(y_i-p_j) + x_{jt}'\beta_i + \xi_{jt} + \epsilon_{ijt}
$$

where $y_i$ is his income, $p_j$ is price, $x_{jt}$ is a vector of observable product characteristics, $\xi_{jt}$ is the unobservable average utility from consuming product $j$ in the population, and $\epsilon_{ijt}$ is the idiosyncratic error term. 

Note that, the coefficient $\beta_i$ is individual-specific. We may interested in the "average taste" for the total population. Hence, we decompose it into two parts and rewrite our utility representation:

\begin{align}
u_{ijt} &= \alpha log(y_i-p_j) + x_{jt}'\bar\beta + \sum_k\sigma_kx_{jk}v_{ik} + \xi_{jt} +  \epsilon_{ijk} \\
        &= \alpha log(y_i-p_j) + \delta_{jt} +  \sum_k\sigma_kx_{jk}v_{ik} +  \epsilon_{ijk}
\end{align}

where $\delta_{jt} =x_{jt}'\bar\beta + \xi_{jt}  $ is the mean utility, $(\zeta_i,\epsilon_i) = (v_{i1},...v_{ik};\epsilon_{i0},...\epsilon_{iJ})$ are random variables with mean zero. In this practice, we assume $\zeta_i$ is standard normal and $\epsilon_i$ is T1EV.

One caveat is that, when $y_i<p_i$, e.g. a worker's income is less than the price of an expensive car, this will cause a problem. Therefore, we modify the utiliy function as:

\begin{align}
u_{ijt} &= \delta_{jt} +  \sum_k\sigma_kx_{jk}v_{ik} +  \epsilon_{ijk} -\alpha \frac{p_{jt}}{y_i}
\end{align}

For the outside good (not buying):
\begin{align}
    u_{i0t} = \alpha log(y_i) + \xi_0 + \sigma_0v_{i0} + \epsilon_{io},  \forall t \in T
\end{align}

The mean utility of outside good is normalized to 0 for simplicity.

The parameters of interest $\theta = \{\theta_1, \theta_2\}$ has two parts: Ones that for population $\theta_1 = \bar\beta$ (since it can be estimated in a linear form, it is called "linear parameters"), and ones for idiosyncratic variances $\theta_2 = \{\alpha; \sigma_1,...\sigma_k\}$ (we call them "nonlinear parameters").


Since $\epsilon$ is T1EV and each consumer can only buy one good, the predicted market share is then given by a mixed logit form:

\begin{align}
\hat s_{jt} &= \int\mathbb1\{u_{ijt}\geq u_{ikt}, \forall k\neq j\}dF(y_i, \zeta_i) \\
       &= \int \frac{exp\{\alpha log(y_i-p_j) + \delta_{jt} + \sum_k\sigma_kx_{jk}v_{ik} \} }{1 + \sum_{l=1}^Jexp\{\alpha log(y_i-p_l) + \delta_{lt} + \sum_k\sigma_kx_{lk}v_{ik} \}}dF(y_i, \zeta_i)\\
       &= \sum_{i=1}^{N}\frac{exp\{\alpha log(y_i-p_j) + \delta_{jt} + \sum_k\sigma_kx_{jk}v_{ik} \} }{1 + \sum_{l=1}^Jexp\{\alpha log(y_i-p_l) + \delta_{lt} + \sum_k\sigma_kx_{lk}v_{ik} \}}
\end{align}

where N is the number of simulation draws in each market.

Actually, real market share $s_{jt}$ is observable and we should let our predicted share equalize the real share $\hat s_{jt} = s_{jt}$.


Note that, $\hat s_{jt}(\delta_{jt})$ is a function of $\delta_{jt}$, and we can invert it to obtain a constraction mapping (which is proved by BLP(1995)):

\begin{align}
\delta_{jt}^{h+1} = \delta_{jt}^h + ln(s_{jt}) - ln(\hat s_{jt}(\delta_{jt}^h))
\end{align}

Hence, given nonlinear parameters $\theta$, we can obtain the mean utility $\delta$, which furthermore implies a linear equation  $\delta_{jt} =x_{jt}'\bar\beta + \xi_{jt}  $. We can run regression to obtain the linear parameters $\bar\beta$.

However, $\mathbb E[\xi_{jt}|x_{jt}] \neq 0$ brings the endogeneity problem. We use characterstics of other goods in the same market as instruments $Z_{d}$ suggested by BLP(1995).

### Supply Side:

We assume there are $F$ firms, each of which product a subset $\mathcal J_f$ of the $J$ goods. The cost characteristics are decomposed into a subset which is observed by econometrician $w_j$, and an unobserved component $\omega_j$. Note that $x_j$ for consumers may be part of $w_j$, and $\omega_j$ is correlated with $\xi_j$. 

We assume the marginal cost of good $j$ can be written as:
\begin{align}
ln(mc_j) = w_j\gamma+\omega_j
\end{align}
where $\gamma$ is a vector of parameters to be estimated.

The profit of firm $f$ is given by:
\begin{align}
\Pi_f = \sum_{j\in\mathcal J_f} (p_j-mc_j)\cdot Ms_j(p,x,\xi,\theta)
\end{align}

where $M$ is the total number of consumers at a given market.

Our FOC is then
\begin{align}
s_j + \sum_{r\in\mathcal J_f}(p_r-mc_r)\frac{\partial s_r}{\partial p_j} = 0, \forall j\in\mathcal J_f
\end{align}

This implies the price-cost markups $b(p,x,\xi,\theta) = p-mc$ can be expressed as:
\begin{align}
b(p,x,\xi,\theta) = \Omega^{-1}s(p,x,\xi,\theta)
\end{align}

where $\Omega_{jr} = -\frac{\partial s_r}{\partial p_j}$ if $r$ and $j$ are produced by the same firm and $\Omega_{jr} = 0$ otherwise.

Hence, we have the regression equation as

\begin{align}
ln(p-b(p,x,\xi,\theta) ) = w\gamma+\omega
\end{align}

Notice that, we still need to instrumenting for $w$ since cost characteristics may be correlated to unobserved disturbance. BLP uses all other products' characteristics as instrument $Z_s$ since products that face good substitudes will tend to have lower markups.

## 2. Estimation Procedure

We do the estimation using **Nested Fixed Point Algorithm**:

Outer loop: Search over nonlinear parameters $\theta_2$

Inner loop: for given $\theta_2$:
* Use contraction mapping to find mean utilities $\hat\delta$ given market share $s$
* Use $\hat\delta$ and the demand instrument $Z_d$ to find linear paramters $\hat\theta_1$ and residual $\hat\xi$
* Compute markup $b(\theta)$, use it and the supply instrument $Z_s$ to run IV regression to find $\hat\omega$
* Form the GMM objective function of $\hat \theta = \text{argmin}_{\theta\in\Theta} Z'\hat {G}'W\hat GZ$, where $Z = (Z'_d, Z'_s)'$ and $\hat G = (\hat{\xi}', \hat{\omega}')'$, since IVs are orthogonal to error terms.

Note that, we need to conduct 2-step GMM since we need to obtain the optimal weighting matrix from the first step. 

The inital weighting matrix is set to $W_0 = ZZ'$ following the suggestion in appendix of Nevo's practitioners' guide.

The (feasible) optimal weighting matrix is $\tilde W = Z'\hat {G}'\hat GZ$.


## 3. Define Functions

In [1]:
import scipy
import time
import pickle
import warnings
import pandas as pd
import numpy as np
import multiprocessing as mp
from scipy.optimize import minimize
from numba import jit, njit, prange
from sklearn.linear_model import LinearRegression

warnings.filterwarnings('ignore')

The following cells is for data cleaning and create necessary variables for estimation.

In [2]:
# Read the dataframe
df = pd.read_csv("blp_1995_data.csv")
df = df.drop(df.columns[0], axis = 1)

# create ln of characteristics for supply variables
df[["ln_hpwt", "ln_space", "ln_mpg", "ln_mpd", "ln_price"]] = \
df[["hpwt", "space", "mpg", "mpd", "price"]].apply(lambda x: np.log(x))

df["trend"] = df.market.map(lambda x: x + 70) # now trend == year

df["cons"] = 1

df["s_0"] = np.log(1 - df.share.groupby(df["model_year"]).transform("sum"))

df["s_i"] = np.log(df.share)
df["diff"] = df.s_i - df.s_0
df["diff_2"] = np.log(df.share) - np.log(df.share_out)
df["ln_price"] = np.log(df.price)

df.head()

modelvec   newmodv  model_year   id  firmid  market      hpwt   space  air  \
0   AMGREM  AMGREM71          71  129      15       1  0.528997  1.1502    0   
1   AMHORN  AMHORN71          71  130      15       1  0.494324  1.2780    0   
2   AMJAVL  AMJAVL71          71  132      15       1  0.467613  1.4592    0   
3   AMMATA  AMMATA71          71  134      15       1  0.426540  1.6068    0   
4   AMAMBS  AMAMBS71          71  136      15       1  0.452489  1.6458    0   

        mpd  ...  ln_space    ln_mpg    ln_mpd  ln_price  trend  cons  \
0  1.888146  ...  0.139936  0.528862  0.635595  1.596515     71     1   
1  1.935989  ...  0.245296  0.553885  0.660618  1.707662     71     1   
2  1.716799  ...  0.377888  0.433729  0.540462  1.961311     71     1   
3  1.687871  ...  0.474245  0.416735  0.523468  1.922716     71     1   
4  1.504286  ...  0.498227  0.301585  0.408318  2.189237     71     1   

        s_0       s_i      diff    diff_2  
0 -0.171483 -6.858013 -6.686531 -6.730300  
1 -0.171483 -7.308233 -7.136750 -7.180520  
2 -0.171483 -7.983628 -7.812146 -7.855915  
3 -0.171483 -7.557843 -7.386360 -7.430130  
4 -0.171483 -7.724201 -7.552718 -7.596488  

[5 rows x 30 columns]

For demand side, product characteristics X includes HP/Weight, air, MP$, space and a constant.

For supply side, cost characteristics W includes ln(HP/Weight), ln(MPG), ln(space), air, trend and a constant.

Also, we obtain income means for 20 markets (years) and a standard deviation of income from CPS.

In [3]:
# variables for demand side
X = df[["cons", "hpwt", "air", "mpd", "space"]].values

# variables for supply side
W = df[["cons", "ln_hpwt", "air", "ln_mpg", "ln_space", "trend"]].values

# price
p = df.price.values

# number of goods per market
J = df.groupby("year").sum().cons.values

# number of draws per market
N = 500

# number of markets
T = len(J)

# Estimated log income means and standard deviation for years 1971 - 1990 (from CPS)
incomeMeans = [2.01156, 2.06526, 2.07843, 2.05775, 2.02915, 2.05346, 2.06745,
               2.09805, 2.10404, 2.07208, 2.06019, 2.06561, 2.07672, 2.10437, 2.12608, 2.16426,
               2.18071, 2.18856, 2.21250, 2.18377]
sigma_v = 1.72

# number of terms that have the random coefficient
#  according to table 4, this is constant, hp/wt, air, mp$, size, price
k = 5

# markets for itj
markets = df.market.values

# unique markets
unique_mkts = np.unique(df.market)

# firms
firms = np.reshape(df.firmid.values, (-1,1))

I. Simulate $N$ individuals' income $y_{i}$ for each market $t$. 

We assume $y_i$ is log-normal:

In [4]:
# set seed
np.random.seed(66)

m_t = np.repeat(incomeMeans, N)

# matrix of simulated values
#  number of rows = number of simulations
#  treat last column is price/income
# note that BLP treat it as the same individuals in the market across all years (Nevo 2000)

# different draws for each market
V = np.reshape(np.random.standard_normal((k + 1) * N * T), (T * N, k + 1))


# income if we have different draws per market
y_it = np.exp(m_t + sigma_v * V[:, k]).reshape(T,N).T

# draws for income if same draws in every market
# y_it = np.exp(m_t + sigma_v * np.tile(V[:, k], len(incomeMeans))).reshape(T,N).T

II. Define a function to compute the predicted markets share $\hat s_{jt}$ given required data and parameters:

In [5]:
# the loops that calculate utility in a separate function so that it can be
#  run in parallel. 
@jit
def util_iter(out, x, v, p, y, delta, theta_2, J, T, N):
    # first iterate over the individuals 
    for i in prange(N):
        # iterator through t and j
        tj = 0
        
        # iterate over the markets
        for t in prange(T):
            # market size of market t
            mktSize = J[t]
            
            # income for individual i in market t
            y_im = y[i, t]
            
            # iterate over goods in a particular market
            for j in prange(mktSize):
                out[tj, i] = delta[tj] + \
                v[N * t + i, 0] * theta_2[0] * x[tj, 0] + \
                v[N * t + i, 1] * theta_2[1] * x[tj, 1] + \
                v[N * t + i, 2] * theta_2[2] * x[tj, 2] + \
                v[N * t + i, 3] * theta_2[3] * x[tj, 3] + \
                v[N * t + i, 4] * theta_2[4] * x[tj, 4] - \
                theta_2[5] / y_im * p[tj]
                
                tj += 1
    return out

# computes indirect utility given parameters
#  x: matrix of demand characteristics
#  v: monte carlo draws of N simulations
#  p: price vector
#  y: income of individuals
#  delta: guess for the mean utility
#  theta_2: non-linear params (sigma - can think of as stdev's)
#  J: vector of number of goods per market
#  T: numer of markets
#  N: number of simulations

@jit
def compute_indirect_utility(x, v, p, y, delta, theta_2, J, T, N):
    # make sure theta_2 are positive
    theta_2 = np.abs(theta_2)
    
    # output matrix
    out = np.zeros((sum(J), N))
    
    # call the iteration function to calculate utilities
    out = util_iter(out, x, v, p, y, delta, theta_2, J, T, N)
     
    return out

In [6]:
# computes the implied shares of goods in each market given inputs
# same inputs as above function

@jit
def compute_share(x, v, p, y, delta, theta_2, J, T, N):
    q = np.zeros((np.sum(J), N))
    
    # obtain vector of indirect utilities
    u = compute_indirect_utility(x, v, p, y, delta, theta_2, J, T, N)
    
    # exponentiate the utilities
    exp_u = np.exp(u)
    
    # pointer to first good in the market
    first_good = 0
            
    for t in range(T):
        # market size of market t
        mktSize = J[t]

        # calculate the numerator of the share eq
        numer = exp_u[first_good:first_good + mktSize,:]

        # calculate the denom of the share eq
        denom = 1 + numer.sum(axis = 0)    
          
        # calculate the quantity each indv purchases of each good in each market
        q[first_good:first_good + mktSize,:] = numer/denom
        
        first_good += mktSize
    
    # to obtain shares, assume that each simulation carries the same weight.
    # this averages each row, which is essentially computing the sahres for each
    #  good in each market. 
    s = np.matmul(q, np.repeat(1/N, N))
    
    return [q,s]

III. Define the function that uses contraction mapping to find $\delta_{jt}$ given $s_{jt}$

In [7]:
# define a class so I can repeatedly update the delta value
class delta:
    def __init__(self, delta):
        self.delta = delta

# initialize a delta object using the delta_0 values

# initial delta_0 estimate: log(share) - log(share outside good)
delta_0 = df.diff_2.values
d = delta(delta_0)

In [8]:
@jit
def solve_delta(s, x, v, p, y, delta, theta_2, J, T, N, tol):
    # define the tolerance variable
    eps = 10
    
    # renaming delta as delta^r
    delta_old = delta
    
    while eps > tol:
        # obtain predicted shares and quantities
        q_s = compute_share(x, v, p, y, delta_old, 
                            theta_2, J, T, N)
        
        # extract the shares
        sigma_jt = q_s[1]
        
        # step 2: use contraction mapping to find delta
        delta_new = delta_old + np.log(s/sigma_jt)
        
        # update tolerance
        eps = np.max(np.abs(delta_new - delta_old))
        
        delta_old = delta_new.copy()
        
        return delta_old
    

IV. Define a function to compute marginal cost:

Recall that, $s_j\approx \frac{1}{N}\sum_{i=1}^N\frac{exp(\tilde u_{ij})}{1+\sum_{k=1}^{J}exp(\tilde u_{ik})}$, where $\tilde u_{ij} = \delta_{j} +  \sum_k\sigma_kx_{jk}v_{ik} -\alpha \frac{p_{j}}{y_i}$ is the indirect utility net of logit shock.

Then $\frac{\partial s_{j}}{\partial p_j} = \frac{1}{N}\sum_{i=1}^N\frac{\alpha}{y_i}(s_{ij}^2-s_{ij})$ and $\frac{\partial s_{j}}{\partial p_k} = \frac{1}{N}\sum_{i=1}^N\frac{\alpha}{y_i} s_{ij} s_{ik}$, where $s_{ij}$ is the individual share of consumer $i$ on product $j$.

Write in matrix form, we have

\begin{align*}
\Omega \approx \frac{1}{N}\sum_{i=1}^N\frac{\alpha}{y_i}\cdot \mathcal H \cdot (s_i s_i'-diag(s_i)) 
\end{align*}

where $\mathcal H$ is the ownership matrix, and $s_i$ is the indivual share of simulated consumer $i$.

After obtaining $\Omega$, we can compute marginal cost by:
\begin{align*}
mc = p-b = p - \Omega^{-1}s
\end{align*}

In [9]:
# calculates the marginal costs given probabilities and shares
#  q_s: output of compute share, a list of probabilities matrix(q) and shares vector(s)
#  firms: vector of firms operating in each market (length is JxT)
#  marks: vector of unique markets (length T)
#  markets: vector indicating observation in which market (length JxT)

@jit
def calc_mc(q_s, firms, p, y, alpha, J, T, N, unique_mkts, markets):
    
    # declare output vector
    out = np.zeros((np.sum(J)))
    
    # make sure the value of alpha is positive
    alpha = np.abs(alpha)
    
    # read in quantities
    q = q_s[0]
    
    # read in shares
    s = q_s[1].reshape((-1,1))
    
    # reshape some vectors into column vectors
    p = p.reshape((-1,1))
    
    # iterate over markets
    for m in unique_mkts:
        # obtain list of firms operating in that market/year
        firm_yr = firms[markets == m]
        
        # obtain list of prices of goods in that market/year
        price = p[markets == m]
        
        # J_t x J_t block matrix of 1's indicating goods belonging to same firm in that market/year
        # Also known as the ownership matrix
        same_firm = np.equal(firm_yr, np.transpose(firm_yr))
        
        # obtain matrix of probabilities for all simulations for goods in that 
        #  market/year
        yr = q[markets == m,:]
        
        # obtain number of goods in that market
        nobs = np.size(yr, 0)
        
        # this is the omega matrix initializing        
        grad = np.zeros((nobs, nobs))
        
        # calculate the omega matix by iterating through all individuals
        #  Omega matrix is cross-price deriv element-wise product with ownership matrix
        for i in range(N):
            yr_i = yr[:, i].reshape((-1, 1))
            grad += alpha / y[i, m - 1] * same_firm * 1/N * (yr_i @ yr_i.T - np.diag(yr[:,i]))
        
        # Omega matrix actually requires negative cross price derivs
        subMatrix = -grad
        
        # now obtain the marginal costs
        b = np.linalg.inv(subMatrix) @ s[markets == m]
        mc = price - b
        mc[mc < 0] = .001
        
        # update entries in the output vector
        out[markets == m] = mc.flatten()
        
    return out

V. Define a function to generate instruments used by BLP(1995):

The instrument has two parts:

total_firms contains a vector of all summed product/cost characteristics produced by the same firm.

total_mkts contains a vector of all summed product/cost characteristics produced by all firms in the market.

In [10]:
# generate instruments for BLP paper
# One can also use packages to generate more "optimal" instruments instead, like Hausmann instruments
# A source of instruments exists in the Conlon and Gortmaker's pyblp package
def gen_iv(inx, firms, marks, markets):
    totMarket = np.zeros((np.size(inx, axis = 0), np.size(inx, axis = 1)))
    totFirm = np.zeros((np.size(inx, axis = 0), np.size(inx, axis = 1)))
    
    for m in marks:
        sub = inx[markets == m, :]
        firminfo = firms[markets == m]
        same_firm = np.equal(firminfo, np.transpose(firminfo))
        
        z_1 = np.zeros((np.size(sub,axis = 0), np.size(sub, axis = 1)))
        
        for i in range(np.size(sub, axis = 1)):
            z_1[:,i] = (sub[:,i].reshape((-1,1)) * same_firm).T.sum(axis = 0)
        
        totFirm[markets == m,:] = z_1
        
        z_1 = np.zeros((np.size(sub,axis = 0), np.size(sub, axis = 1)))
        
        for i in range(np.size(sub, axis = 1)):
            z_1[:,i] = (sub[:,i].reshape((-1,1)) * (same_firm + np.logical_not(same_firm))).sum(axis = 0)
            
        totMarket[markets == m, :] = z_1
        
    return [totFirm, totMarket]


VI: Define objective function that can search over nonlinear parameters $\theta_2$:

1: Given non-linear paramerters $\theta_2$, actual market share $s$, solve the optimal $\hat\delta$

2: Compute log marginal cost $log(mc)$. 

3: Stack $\mathbf y = (\hat\delta', log(mc)')'$, $X = (X_d', X_s')'$, $Z = (Z_d', Z_s')'$.

4: Obtain the linear paramter $\hat\theta_1 = (X'ZWZ'X)^{-1}X'ZWZ'Y$ by GMM:

  Note that we have $\mathbb E[z_i(y_i-x_i'\theta_1)] = 0$
  
  Then we have the sample analog $\frac{1}{N}Z'Y-\frac{1}{N}Z'X\theta_1 = 0$. However, since $d_z>d_{\theta_1}$, this is a over-identified linear system, the equality cannot hold. We can estimate $\theta_1$ using GLS (Generalized Least Squares):
  
  Denote $\eta = Z'Y$, $G = Z'X$, the previous equation can be written as $\eta = G\theta_1 + u$. The estimates of $\theta_1$ is $\hat\theta_1 = (G'WG)^{-1}G'W\eta$, which is equivalent to $\hat\theta_1 = (X'ZWZ'X)^{-1}X'ZWZ'Y$

5: obtain the residual $\hat\xi = \mathbf y - X\hat\theta_1$

6: $\theta_2 = \text{argmin}_{\theta\in\Theta}\hat\xi'Z W Z'\hat\xi$ using $\mathbb E[Z'\xi] = 0$

In [11]:
# If you're looking at the four steps Aviv lists in his appendix, start here
# This is the objective function that we optimize the non-linear parameters over
def objective(theta_2, s, X, V, p, y, J, T, N, marks, markets, tol, 
              Z, Z_s, W, weigh, firms):
    
    obs = np.sum(J)
    
    # Aviv's step 1 & 2:
    d.delta = solve_delta(s, X, V, p, y, d.delta, theta_2, J, T, N, tol)
    
    # obtain the actual implied quantities and shares from converged delta
    q_s = compute_share(X, V, p, y, d.delta, theta_2, J, T, N)
    
    # calculate marginal costs
    mc = calc_mc(q_s, firms, p, y, theta_2[5], J, T, N, marks, markets).reshape((-1,1))
    
    # since we are using both demand and supply side variables,
    #  we want to stack the estimated delta and estimated mc
    y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))
    
    # create characteristics matrix that includes both supply and demand side
    #  with demand characteristics on the bottom left and supply on the top right
    x = scipy.linalg.block_diag(X,W)
    
    # create matrix of supply and demand instruments, again with
    #  demand instruments on the right and supply on the left (top/down changed)    
    z = scipy.linalg.block_diag(Z,Z_s)
    
    # get linear parameters (this FOC is from Aviv's appendix)
    b = np.linalg.inv(x.T @ z @ weigh @ z.T @ x) @ (x.T @ z @ weigh @ z.T @ y2)

    # Step 3: get the error term xi (also called omega)
    xi_w = y2 - x @ b
    
    # computeo g_bar in GMM methods
    g = z.T @ xi_w
    
    obj = float( g.T @ weigh @ g)
   
    #print([theta_2, obj])
    
    return obj

### 4. Replications

#### Table I: Descriptive Statistics

In [12]:
# create table
table_1 = pd.DataFrame()

# calculate weighted means of the following column with quantity weights
table_1[[
    "P", "Dom", "Japan", "Eu", "HP_Wt", "Size", "Air", "MPG", "MPD", "drop"
   ]] = df[["price", "domestic", "japan", 
    "european", "hpwt", "space", 
    "air", "mpg", "mpd", "quantity"]] \
    .groupby(df.year) \
    .apply(lambda x: pd.Series(np.average(x, weights=x["quantity"], axis = 0)))

# count number of models per year/market
table_1.insert(0, "num_models", df.groupby("year").sum().cons.values)

# mean quantity per year/market
table_1.insert(1, "Q", df.quantity.groupby(df.year).mean()) 

# delete the extraneous weighted quantity column
table_1.drop('drop', axis=1, inplace=True)

In [13]:
# round the table to 3 digits to emulate the paper
np.round(table_1, 3)

num_models        Q       P    Dom  Japan     Eu  HP_Wt   Size    Air  \
year                                                                          
71            92   86.892   7.868  0.866  0.057  0.077  0.490  1.496  0.000   
72            89   98.623   7.979  0.892  0.042  0.066  0.391  1.510  0.014   
73            86   92.785   7.535  0.932  0.040  0.028  0.364  1.529  0.022   
74            72  105.119   7.506  0.887  0.050  0.064  0.347  1.510  0.026   
75            93   84.775   7.821  0.853  0.083  0.064  0.337  1.479  0.054   
76            99   93.382   7.787  0.876  0.081  0.043  0.338  1.508  0.059   
77            95   97.727   7.651  0.837  0.112  0.051  0.340  1.467  0.032   
78            95   99.444   7.645  0.855  0.107  0.039  0.346  1.405  0.034   
79           102   82.742   7.599  0.803  0.158  0.038  0.348  1.343  0.047   
80           103   71.567   7.718  0.773  0.191  0.036  0.350  1.296  0.078   
81           116   62.030   8.349  0.741  0.213  0.046  0.349  1.286  0.094   
82           110   61.893   8.831  0.714  0.235  0.051  0.347  1.277  0.134   
83           115   67.878   8.821  0.734  0.215  0.051  0.351  1.276  0.126   
84           113   85.933   8.870  0.783  0.179  0.038  0.361  1.293  0.129   
85           136   78.143   8.938  0.761  0.191  0.048  0.372  1.265  0.140   
86           130   83.756   9.382  0.733  0.216  0.050  0.379  1.249  0.176   
87           143   67.667   9.965  0.702  0.245  0.052  0.395  1.246  0.229   
88           150   67.078  10.069  0.717  0.237  0.045  0.396  1.251  0.237   
89           147   62.914  10.321  0.690  0.261  0.049  0.406  1.259  0.289   
90           131   66.377  10.337  0.682  0.276  0.043  0.419  1.270  0.308   

        MPG    MPD  
year                
71    1.662  1.849  
72    1.619  1.875  
73    1.589  1.818  
74    1.567  1.452  
75    1.584  1.503  
76    1.759  1.696  
77    1.947  1.835  
78    1.982  1.929  
79    2.061  1.657  
80    2.215  1.466  
81    2.363  1.559  
82    2.440  1.817  
83    2.601  2.087  
84    2.469  2.117  
85    2.261  2.024  
86    2.416  2.856  
87    2.327  2.789  
88    2.334  2.919  
89    2.310  2.806  
90    2.270  2.852

#### Table III: Results with Logit Demand and Marginal Cost Pricing

1. The first column shows the result of the OLS logit demand:
\begin{align}
ln(s_j)-ln(s_0) = -\alpha p_j + x_j'\beta + \xi_j
\end{align}

In [14]:
# table 3 column 1
table3_col1 = LinearRegression().fit(df[["hpwt", "air", "mpd", "space", "price"]], df.diff_2)
np.hstack((table3_col1.intercept_, table3_col1.coef_))

array([-10.07300751,  -0.12309488,  -0.03441478,   0.26546568,
         2.34191416,  -0.08860627])

2. The second column shows the result of IV logit demand: (we use 2-step GMM for estimation)

In [15]:
# IV Reg in table 3 column 2

tempDemand = gen_iv(X, firms, unique_mkts, markets)
tempSupply = gen_iv(W, firms, unique_mkts, markets)

Z = np.hstack((X, tempDemand[0], tempDemand[1]))
baseData = np.hstack((p.reshape((-1,1)), X))

Z_s = np.hstack((W, tempSupply[0], tempSupply[1], df.mpd.values.reshape((-1,1))))

X_base = np.hstack((X, p.reshape((-1,1))))

ZX = Z.T @ X_base

bx1 = np.linalg.inv(ZX.T @ ZX)@ ZX.T @ Z.T @ delta_0 # first round IV regression using identity weighting matrix

e = delta_0 - X_base @ bx1 # obtain the residual

g_ind = e.reshape((-1,1)) * Z

demean = g_ind - g_ind.mean(axis=0).reshape((1,-1))

vg = demean.T @ demean / demean.shape[0] # this is actually the variance of g

w0 = np.linalg.inv(vg) # obtain feasible optimal weighting matrix

table3_col2 = np.linalg.inv(ZX.T @ w0 @ ZX) @ ZX.T @ w0 @ Z.T @ delta_0 # second round IV regression
table3_col2

array([-9.27629294,  1.94935115,  1.28739148,  0.05456147,  2.35760254,
       -0.21578695])

3. The third column shows the result of OLS ln(price) on $w$:
\begin{align}
ln(p) = w'\gamma + \omega
\end{align}

In [16]:
# table 3 column 3
table3_col3 = LinearRegression().fit(
    df[["ln_hpwt", "air", "ln_mpg", "ln_space", "trend"]],
    df.ln_price)
np.hstack((table3_col3.intercept_, table3_col3.coef_))

array([ 1.88192125,  0.52033668,  0.6797513 , -0.47064027,  0.12482708,
        0.01283075])

#### Table IV: Esimated Parameters of the Demand and Pricing Equations (column 3)

In [17]:
# obtain block-diag matrix of supply and demand instruments
z = scipy.linalg.block_diag(Z,Z_s)

# Recommended initial weighting matrix from Aviv's appendix
w1 = np.linalg.inv(z.T @ z)

In [18]:
# # run objective function once to see if it is working
# initial parameter guess (from BLP(1995))
theta_2 = [3.612, 4.628, 1.818, 1.050, 2.056, 43.501]

t0 = time.time()

obj = objective(theta_2, 
                df.share.values, 
                X, V, p, y_it, J, T, N, unique_mkts, markets, 1e-4, 
              Z, Z_s, W, w1, firms)


time.time() - t0

6.475566625595093

In [19]:
# constraints for the minimization problem
#  not needed because utility considers abosolute value of params before calculating

# search over parameters that minimize the objective function
t1 = time.time()

# set bounds for optimization (not entirely needed but oh well)
bnds = ((0,np.inf), (0,np.inf), (0,np.inf), 
        (0,np.inf), (0,np.inf), (5,np.inf))

res_init_wt = minimize(objective,
                      theta_2, 
                      args = (df.share.values, X, V, p, y_it, 
                              J, T, N, unique_mkts, markets, 1e-4, 
                              Z, Z_s, W, w1, firms), 
                      bounds = bnds,
                      method = "L-BFGS-B",
                      options = {'maxiter': 1000, 'maxfun': 1000, 'eps': 1e-3},
                      tol = 1e-4)
    

    
time.time() - t1

99.45681858062744

In [20]:
# Saving
# outfile = open("res_init_wt_bfgs.pickle", "wb")
# pickle.dump(res_init_wt, outfile)
# outfile.close()

# Reading
with open("res_init_wt_bfgs.pickle", "rb") as infile:
    res_init_wt = pickle.load(infile)


In [21]:
res_init_wt.x

array([ 3.612,  4.628,  1.818,  1.05 ,  2.056, 43.501])

In [22]:
obs = np.sum(J)

# approximate optimal weighting matrix
params_2 = res_init_wt.x

# calculate mean utility given the optimal parameters (with id weighting matrix)
d.delta = solve_delta(df.share.values, X, V, p, y_it, 
                        d.delta, params_2, J, T, N, 1e-5)

# calculate probabilities and shares given the optimal params (w/ id weight matrix)
q_s = compute_share(X, V, p, y_it, d.delta, params_2, J, T, N)

# calculate marginal costs
mc = calc_mc(q_s, firms, p, y_it, params_2[5], J, T, N, unique_mkts, markets).reshape((-1,1))

y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))
x = scipy.linalg.block_diag(X,W)
z = scipy.linalg.block_diag(Z,Z_s)

# this is the first order condition that solves for the linear parameters
b = np.linalg.inv(x.T @ z @ w1 @ z.T @ x) @ (x.T @ z @ w1 @ z.T @ y2)

# obtain the error
xi_w = y2 - x @ b


# update weighting matrix
g_ind = z * xi_w
vg = g_ind.T @ g_ind / obs

# obtain optimal weighting matrix
weight = scipy.linalg.inv(vg)

In [23]:
# now search for optimal parameters with the optimal weighting matrix
t1 = time.time()

res = minimize(objective,
              theta_2, 
              args = (df.share.values, X, V, p, y_it, 
                      J, T, N, unique_mkts, markets, 1e-4, 
                      Z, Z_s, W, weight, firms), 
              bounds = bnds,
              method = "L-BFGS-B",
              options = {'maxiter': 1000, 'maxfun': 1000, 'eps': 1e-3},
              tol = 1e-4)

time.time() - t1

113.10295414924622

In [24]:
# Saving
#outfile = open("res_bfgs.pickle", "wb")
#pickle.dump(res_init_wt, outfile)
#outfile.close()

# Reading
with open("res_bfgs.pickle", "rb") as infile:
    res_init_wt = pickle.load(infile)

1. Non-linear parameter estimates: Std. Deviations ($\sigma_\beta$'s)

In [25]:
params_3 = res.x
params_3

array([ 4.48567094,  4.73803617,  1.85556832,  1.04868037,  2.30903141,
       43.49958848])

2. Linear parameters:

First 5 are the demand side means (Constant, HP/Weight, Air, MP$, Size)

Last 6 are the cost side params (Constant, ln(HP/Weight), Air, ln(MPG), ln(Size), Trend)

In [26]:
d.delta = solve_delta(df.share.values, X, V, p, y_it, 
                        d.delta, params_3, J, T, N, 1e-4)
q_s = compute_share(X, V, p, y_it, d.delta, params_3, J, T, N)
    
mc = calc_mc(q_s, firms, p, y_it, params_3[5], J, T, N, unique_mkts, markets).reshape((-1,1))
    
y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))

In [27]:
# linear parameters
# compare parameters to Table iv, column 3
#  first 5 are the demand side means (Constant, HPWT, Air, MP$, Size)
#  last 6 are the cost side params (Constant, ln(HPWT), Air, ln(MPG), ln(Size), Trend)
b = np.linalg.inv(x.T @ z @ weight @ z.T @ x) @ (x.T @ z @ weight @ z.T @ y2)
b

array([[-6.42322037],
       [ 3.01177244],
       [ 0.56620007],
       [-0.17486551],
       [ 3.30623812],
       [ 1.19084377],
       [ 0.50412849],
       [ 0.59499734],
       [-0.45676616],
       [-0.2029649 ],
       [ 0.01709775]])

In [28]:
# non-linear parameters - these are the sigma estimates and alpha in table iv of BLP
# (constant, HPWT, Air, MP$, Size, ln(y-p))
res.x

array([ 4.48567094,  4.73803617,  1.85556832,  1.04868037,  2.30903141,
       43.49958848])

In [29]:
# average markup (compare to table 12 of Conlon and Gortmaker (2019))
np.mean((p.flatten() - mc.flatten())/p.flatten())

0.3134736956736436

#### Table VI: Own- and Cross-Price Semi-Elasticities:

(the change of percentage market share given the  \$1k price change)

$\epsilon_{ij} = \frac{\partial s_i}{\partial p_j} \cdot \frac{100}{s_i}$

In [30]:
share_deriv = []
q = q_s[0]
s = q_s[1]
for m in unique_mkts:
    # obtain list of firms operating in that market/year
    firm_yr = firms[markets == m]

    # obtain list of prices of goods in that market/year
    price = p[markets == m]

    # J_t x J_t block matrix of 1's indicating goods belonging to same firm
    #  in that market/year
    # Also known as the ownership matrix
    same_firm = np.equal(firm_yr, np.transpose(firm_yr))

    # obtain matrix of probabilities for all simulations for goods in that 
    #  market/year
    yr = q[markets == m,:]

    # obtain number of goods in that market
    nobs = np.size(yr, 0)

    # this is the omega matrix initializing        
    deriv_m = np.zeros((nobs, nobs))

    # calculate the omega matix by iterating through all individuals
    #  Omega matrix is cross-price share deriv element-wise product with ownership matrix
    for i in range(N):
        yr_i = yr[:, i].reshape((-1, 1))
        deriv_m += params_3[5] / y_it[i, m - 1] * 1/N * (yr_i @ yr_i.T - np.diag(yr[:,i]))
        
    share_deriv.append(deriv_m)     

In [31]:
# obtain the mazda 323 own-price deriv in 1990
mz323_deriv = (share_deriv[19][df.modelvec[markets == 20] == "MZ323"]).flatten()[df.modelvec[markets == 20] == "MZ323"]

# obtain the bmw 735i own-price deriv in 1990
bw735i_deriv = (share_deriv[19][df.modelvec[markets == 20] == "BW735i"]).flatten()[df.modelvec[markets == 20] == "BW735i"]

In [32]:
# obtain the mazda 323 mkt share in 1990
mz323_s = s[(markets == 20) & (df.modelvec == "MZ323")]

# obtain the bmw 735i market share in 1990
bw735i_s = s[(markets == 20) & (df.modelvec == "BW735i")]

In [33]:
# compare with table VI, first row first column of BLP
mz323_deriv/ mz323_s * 100

array([-127.47253219])

In [34]:
# compare with table VI, last row last column of BLP
bw735i_deriv/bw735i_s * 100

array([-7.18013863])

In [35]:
# now we create all of table VI
# extract all of the cars
table_vi_cars = ["MZ323", "NISENT", "FDESCO", "CVCAVA", "HDACCO", "FDTAUR", "BKCENT",
                "NIMAXI", "ACLEGE", "LNTOWN", "CDSEVI", "LXLS40", "BW735i"]

In [36]:
# obtain share derivs and shares relevant cars in 1990
deriv_1990 = share_deriv[19]
s_1990 = s[markets == 20]

In [37]:
# initialize the matrix dimensions of table VI
table_vi_mx = np.zeros((len(table_vi_cars), len(table_vi_cars)))

# iterate across cars to obtain table vi
row = 0
for car in table_vi_cars:
    col = 0
    for cars in table_vi_cars:
        table_vi_mx[row, col] = (deriv_1990[df.modelvec[markets == 20] == cars].flatten())[df.modelvec[markets == 20] == car] / \
            s_1990[df.modelvec[markets == 20] == car] * 100
        col += 1
    row += 1    

In [38]:
# store in dataframe for easier viewing
table_vi = pd.DataFrame(np.round(table_vi_mx, 3))

# renaming rows and columns
table_vi.index = table_vi_cars
table_vi.columns = table_vi_cars

In [39]:
table_vi

MZ323   NISENT   FDESCO   CVCAVA  HDACCO  FDTAUR  BKCENT  NIMAXI  \
MZ323  -127.473    1.527    9.282    7.466   2.290   0.893   0.391   0.060   
NISENT    0.710 -111.663    8.791    7.058   2.550   1.017   0.426   0.079   
FDESCO    0.740    1.508 -104.297    6.992   2.600   0.899   0.392   0.067   
CVCAVA    0.582    1.184    6.840 -105.263   2.600   1.400   0.538   0.106   
HDACCO    0.126    0.303    1.799    1.839 -48.370   1.677   0.383   0.250   
FDTAUR    0.066    0.161    0.828    1.319   2.233 -45.357   0.490   0.279   
BKCENT    0.080    0.188    1.010    1.415   1.425   1.368 -57.430   0.727   
NIMAXI    0.014    0.039    0.193    0.313   1.043   0.875   0.815 -31.784   
ACLEGE    0.003    0.011    0.050    0.088   0.641   0.564   0.284   0.481   
LNTOWN    0.001    0.003    0.014    0.031   0.291   0.348   0.120   0.218   
CDSEVI    0.001    0.005    0.020    0.040   0.380   0.394   0.146   0.319   
LXLS40    0.001    0.004    0.019    0.032   0.345   0.300   0.098   0.237   
BW735i    0.000    0.001    0.005    0.012   0.150   0.167   0.052   0.146   

        ACLEGE  LNTOWN  CDSEVI  LXLS40  BW735i  
MZ323    0.007   0.006   0.002   0.002   0.000  
NISENT   0.012   0.010   0.003   0.003   0.000  
FDESCO   0.009   0.007   0.002   0.003   0.000  
CVCAVA   0.016   0.015   0.005   0.004   0.000  
HDACCO   0.083   0.104   0.030   0.034   0.004  
FDTAUR   0.097   0.165   0.042   0.039   0.006  
BKCENT   0.136   0.159   0.043   0.036   0.005  
NIMAXI   0.258   0.324   0.106   0.098   0.015  
ACLEGE -18.070   0.438   0.153   0.149   0.030  
LNTOWN   0.158 -11.275   0.123   0.156   0.035  
CDSEVI   0.248   0.550 -12.829   0.173   0.040  
LXLS40   0.195   0.565   0.139 -10.266   0.047  
BW735i   0.152   0.497   0.128   0.183  -7.180

### Citations

Berry, S., Levinsohn, J., & Pakes, A. (1995). Automobile prices in market equilibrium. Econometrica: Journal of the Econometric Society, 841-890.

Nevo, A. (2000). A practitioner's guide to estimation of random‐coefficients logit models of demand. Journal of economics & management strategy, 9(4), 513-548.

Ivan Li's website: Replication of the classic BLP (1995). Retrieved June, 2023, from https://www.ivan-li.com/code/blp_1995