# A Replication of BLP(1995)
##### Last update: Dec. 2023 
##### I sincerely thank Ivan Li (https://www.ivan-li.com/) for posting his code for reference. 

### This file replicates the following results in BLP(1995):

* Table I: Descriptive Statistics
* Table III: Results with Logit Demand and Marginal Cost Pricing
* Table IV: Esimated Parameters of the Demand and Pricing Equations (column 3)
* Table VI: A Sample of Estimated Own- and Cross-Price Semi-Elasticities

### Content:

1. [The Model](#1.-The-Model)
1. [Estimation Procedure](#2.-Estimation-Procedure)
1. [Define Functions](#3.-Define-Functions)
1. [Replications](#4.-Replications)
1. [Citations](#Citations)


## 1. The Model ##

### Demand Side:
Suppose there are $T$ markets (each market is a year), and $J_t$ products in each market $t$.

For each consumer $i$, his utility for purchasing product $j$ in market $t$ is given by:

$$
u_{ijt} = \alpha log(y_i-p_j) + x_{jt}'\beta_i + \xi_{jt} + \epsilon_{ijt}
$$

where $y_i$ is his income, $p_j$ is price, $x_{jt}$ is a vector of observable product characteristics, $\xi_{jt}$ is the unobservable average utility from consuming product $j$ in the population, and $\epsilon_{ijt}$ is the idiosyncratic error term. 

Note that, the coefficient $\beta_i$ is individual-specific. We may interested in the "average taste" for the total population. Hence, we decompose it into two parts and rewrite our utility representation:

\begin{align}
u_{ijt} &= \alpha log(y_i-p_j) + x_{jt}'\bar\beta + \sum_k\sigma_kx_{jk}v_{ik} + \xi_{jt} +  \epsilon_{ijk} \\
        &= \alpha log(y_i-p_j) + \delta_{jt} +  \sum_k\sigma_kx_{jk}v_{ik} +  \epsilon_{ijk}
\end{align}

where $\delta_{jt} =x_{jt}'\bar\beta + \xi_{jt}  $ is the mean utility, $(\zeta_i,\epsilon_i) = (v_{i1},...v_{ik};\epsilon_{i0},...\epsilon_{iJ})$ are random variables with mean zero. In this practice, we assume $\zeta_i$ is standard normal and $\epsilon_i$ is T1EV.

One caveat is that, when $y_i<p_i$, e.g. a worker's income is less than the price of an expensive car, this will cause a problem. Therefore, we modify the utiliy function as:

\begin{align}
u_{ijt} &= \delta_{jt} +  \sum_k\sigma_kx_{jk}v_{ik} +  \epsilon_{ijk} -\alpha \frac{p_{jt}}{y_i}
\end{align}

For the outside good (not buying):
\begin{align}
    u_{i0t} = \alpha log(y_i) + \xi_0 + \sigma_0v_{i0} + \epsilon_{io},  \forall t \in T
\end{align}

The mean utility of outside good is normalized to 0 for simplicity.

The parameters of interest $\theta = \{\theta_1, \theta_2\}$ has two parts: Ones that for population $\theta_1 = \bar\beta$ (since it can be estimated in a linear form, it is called "linear parameters"), and ones for idiosyncratic variances $\theta_2 = \{\alpha; \sigma_1,...\sigma_k\}$ (we call them "nonlinear parameters").


Since $\epsilon$ is T1EV and each consumer can only buy one good, the predicted market share is then given by a mixed logit form:

\begin{align}
\hat s_{jt} &= \int\mathbb1\{u_{ijt}\geq u_{ikt}, \forall k\neq j\}dF(y_i, \zeta_i) \\
       &= \int \frac{exp\{\alpha log(y_i-p_j) + \delta_{jt} + \sum_k\sigma_kx_{jk}v_{ik} \} }{1 + \sum_{l=1}^Jexp\{\alpha log(y_i-p_l) + \delta_{lt} + \sum_k\sigma_kx_{lk}v_{ik} \}}dF(y_i, \zeta_i)\\
       &\approx \sum_{i=1}^{NS}\frac{exp\{\alpha log(y_i-p_j) + \delta_{jt} + \sum_k\sigma_kx_{jk}v_{ik} \} }{1 + \sum_{l=1}^Jexp\{\alpha log(y_i-p_l) + \delta_{lt} + \sum_k\sigma_kx_{lk}v_{ik} \}}
\end{align}

where NS is the number of simulation draws in each market.

Actually, real market share $s_{jt}$ is observable and we should let our predicted share equalize the real share $\hat s_{jt} = s_{jt}$.


Note that, $\hat s_{jt}(\delta_{jt})$ is a function of $\delta_{jt}$, and we can invert it to obtain a constraction mapping (which is proved by BLP(1995)):

\begin{align}
\delta_{jt}^{h+1} = \delta_{jt}^h + ln(s_{jt}) - ln(\hat s_{jt}(\delta_{jt}^h))
\end{align}

Hence, given nonlinear parameters $\theta$, we can obtain the mean utility $\delta$, which furthermore implies a linear equation  $\delta_{jt} =x_{jt}'\bar\beta + \xi_{jt}  $. We can run regression to obtain the linear parameters $\bar\beta$.

However, $\mathbb E[\xi_{jt}|x_{jt}] \neq 0$ brings the endogeneity problem. We use characterstics of other goods in the same market as instruments $Z_{d}$ suggested by BLP(1995).

### Supply Side:

We assume there are $F$ firms, each of which product a subset $\mathcal J_f$ of the $J$ goods. The cost characteristics are decomposed into a subset which is observed by econometrician $w_j$, and an unobserved component $\omega_j$. Note that $x_j$ for consumers may be part of $w_j$, and $\omega_j$ is correlated with $\xi_j$. 

We assume the marginal cost of good $j$ can be written as:
\begin{align}
ln(mc_j) = w_j\gamma+\omega_j
\end{align}
where $\gamma$ is a vector of parameters to be estimated.

The profit of firm $f$ is given by:
\begin{align}
\Pi_f = \sum_{j\in\mathcal J_f} (p_j-mc_j)\cdot Ms_j(p,x,\xi,\theta)
\end{align}

where $M$ is the total number of consumers at a given market.

Our FOC is then
\begin{align}
s_j + \sum_{r\in\mathcal J_f}(p_r-mc_r)\frac{\partial s_r}{\partial p_j} = 0, \forall j\in\mathcal J_f
\end{align}

This implies the price-cost markups $b(p,x,\xi,\theta) = p-mc$ can be expressed as:
\begin{align}
b(p,x,\xi,\theta) = \Omega^{-1}s(p,x,\xi,\theta)
\end{align}

where $\Omega_{jr} = -\frac{\partial s_r}{\partial p_j}$ if $r$ and $j$ are produced by the same firm and $\Omega_{jr} = 0$ otherwise.

Hence, we have the regression equation as

\begin{align}
ln(p-b(p,x,\xi,\theta) ) = w\gamma+\omega
\end{align}

Notice that, we still need to instrumenting for $w$ since cost characteristics may be correlated to unobserved disturbance. BLP uses all other products' characteristics as instrument $Z_s$ since products that face good substitudes will tend to have lower markups.

## 2. Estimation Procedure

We do the estimation using **Nested Fixed Point Algorithm**:

Outer loop: Search over nonlinear parameters $\theta_2$

Inner loop: for given $\theta_2$:
* Use contraction mapping to find mean utilities $\hat\delta$ given market share $s$
* Use $\hat\delta$ and the demand instrument $Z_d$ to find linear paramters $\hat\theta_1$ and residual $\hat\xi$
* Compute markup $b(\theta)$, use it and the supply instrument $Z_s$ to run IV regression to find $\hat\omega$
* Form the GMM objective function of $\hat \theta = \text{argmin}_{\theta\in\Theta} Z'\hat {G}'W\hat GZ$, where $Z = (Z'_d, Z'_s)'$ and $\hat G = (\hat{\xi}', \hat{\omega}')'$, since IVs are orthogonal to error terms.

Note that, we need to conduct 2-step GMM since we need to obtain the optimal weighting matrix from the first step. 

The inital weighting matrix is set to $W_0 = ZZ'$ following the suggestion in appendix of Nevo's practitioners' guide.

The (feasible) optimal weighting matrix is $\tilde W = Z'\hat {G}'\hat GZ$.


## 3. Define Functions

We first import data and create required variables:

In [1]:
import scipy
import time
import pickle
import warnings
import pandas as pd
import numpy as np
import multiprocessing as mp
from scipy.optimize import minimize
from numba import jit, njit, prange
from sklearn.linear_model import LinearRegression

warnings.filterwarnings('ignore')

In [2]:
# read the dataframe
df = pd.read_csv("blp_1995_data.csv")
df = df.drop(df.columns[0], axis = 1)

# log transformation of variables
df[["ln_hpwt", "ln_space", "ln_mpg", "ln_mpd", "ln_price"]] = \
df[["hpwt", "space", "mpg", "mpd", "price"]].apply(lambda x: np.log(x))

df["trend"] = df.market.map(lambda x: x+70) # set the value of trend = year
df["cons"] = 1
df["s_0"] = np.log(df.share_out)
df["s_i"] = np.log(df.share)

df["diff"] = df.s_i - df.s_0
df["diff_2"] = np.log(df.share) - np.log(df.share_out)
df["ln_price"] = np.log(df.price)

df.head()


modelvec   newmodv  model_year   id  firmid  market      hpwt   space  air  \
0   AMGREM  AMGREM71          71  129      15       1  0.528997  1.1502    0   
1   AMHORN  AMHORN71          71  130      15       1  0.494324  1.2780    0   
2   AMJAVL  AMJAVL71          71  132      15       1  0.467613  1.4592    0   
3   AMMATA  AMMATA71          71  134      15       1  0.426540  1.6068    0   
4   AMAMBS  AMAMBS71          71  136      15       1  0.452489  1.6458    0   

        mpd  ...  ln_space    ln_mpg    ln_mpd  ln_price  trend  cons  \
0  1.888146  ...  0.139936  0.528862  0.635595  1.596515     71     1   
1  1.935989  ...  0.245296  0.553885  0.660618  1.707662     71     1   
2  1.716799  ...  0.377888  0.433729  0.540462  1.961311     71     1   
3  1.687871  ...  0.474245  0.416735  0.523468  1.922716     71     1   
4  1.504286  ...  0.498227  0.301585  0.408318  2.189237     71     1   

        s_0       s_i      diff    diff_2  
0 -0.127713 -6.858013 -6.730300 -6.730300  
1 -0.127713 -7.308233 -7.180520 -7.180520  
2 -0.127713 -7.983628 -7.855915 -7.855915  
3 -0.127713 -7.557843 -7.430130 -7.430130  
4 -0.127713 -7.724201 -7.596488 -7.596488  

[5 rows x 30 columns]

For demand side, product characteristics $X$ includes HP/Weight, air, MP$, space and a constant.

For supply side, cost characteristics $W$ includes ln(HP/Weight), ln(MPG), ln(space), air, trend and a constant.

Also, we obtain income means for 20 markets (years) and a standard deviation of income from CPS.

In [3]:
# demand side characteristics
X_d = df[["cons", "hpwt", "air", "mpd", "space"]].values

# supply side characteristics
X_s = df[["cons", "ln_hpwt", "air", "ln_mpg", "ln_space", "trend"]].values

# price
p = df.price.values

# number of goods per markets (J_t)
J = df.groupby("year").sum().cons.values

# number of markets (T)
T = len(J)

# number of draws per market
N = 1000

# estimated log(income) means and standard deviation for years 1971 - 1990 (from CPS)
income_means = [2.01156, 2.06526, 2.07843, 2.05775, 2.02915, 2.05346, 2.06745,
               2.09805, 2.10404, 2.07208, 2.06019, 2.06561, 2.07672, 2.10437, 2.12608, 2.16426,
               2.18071, 2.18856, 2.21250, 2.18377]
income_std = 1.72

# number of non-linear parameters = 6
# they are coefficients for {constant, hp/wt, air, mp$, size, price}
k = 6

# market for ijt
markets = df.market.values

# unique markets
unique_mkts = np.unique(df.market)

# firms
firms = np.reshape(df.firmid.values, (-1,1))

I. Simulate $N$ individuals' income $y_{i}$ for each market $t$. 

We assume $y_i$ is log-normal:

In [4]:
np.random.seed(888)

# repeat values in income_means for N times
m_t = np.repeat(income_means, N)

# matrix of simulated values
V = np.reshape(np.random.standard_normal(k*N*T), (T*N,k))

# we use different draws per market
y_it = np.exp(m_t + income_std * V[:, k-1]).reshape(T,N).T

II. Define a function to compute the predicted markets share $\hat s_{jt}$ given required data and parameters:

In [5]:
# the loops that calculate utility in a separate function so that it can be run in parallel 
@jit
def utility_iter(output, x, v, p, y, delta, theta_2, J, T, N):
    # iterate over individuals
    for i in prange(N):
        # iterate over every product in every market
        tj = 0
        for t in prange(T):
            # market size of market t
            mkt_size = J[t]
            
            # income for individual i in market t
            y_im = y[i, t]
            
            for j in prange(mkt_size):
                output[tj, i] = delta[tj] + \
                    v[N * t + i, 0] * theta_2[0] * x[tj, 0] + \
                    v[N * t + i, 1] * theta_2[1] * x[tj, 1] + \
                    v[N * t + i, 2] * theta_2[2] * x[tj, 2] + \
                    v[N * t + i, 3] * theta_2[3] * x[tj, 3] + \
                    v[N * t + i, 4] * theta_2[4] * x[tj, 4] - \
                    theta_2[5] * p[tj] / y_im
                
                tj += 1
                
    return output

In [6]:
#  this function computes indirect utility given parameters
#  x: matrix of demand characteristics
#  v: monte carlo draws of N simulations
#  p: price vector
#  y: income of individuals
#  delta: guess for the mean utility
#  theta_2: non-linear parameters
#  J: vector of number of goods per market
#  T: numer of markets
#  N: number of simulations
#  it returns a matrix (J*T, N) to store the simulated utilities
@jit
def compute_indirect_utility(x, v, p, y, delta, theta_2, J, T, N):
    # make sure theta_2 is positive
    theta_2 = np.abs(theta_2)
    
    # predefine output matrix
    simulated_u = np.zeros((sum(J), N))
    
    simulated_u = utility_iter(simulated_u, x, v, p, y, delta, theta_2, J, T, N)
                
    return simulated_u

In [7]:
# This function compute shares for all goods in all market

@jit
def compute_share(x, v, p, y, delta, theta_2, J, T, N):
    # predefine the matrix of individual shares
    q = np.zeros((np.sum(J), N))
    
    # obtain vector of indirect utilities
    u = compute_indirect_utility(x, v, p, y, delta, theta_2, J, T, N)
    
    # exponentiate the utilities
    exp_u = np.exp(u)
    
    # pointer to the first good in market t
    first_good = 0
    
    for t in range(T):
        mkt_size = J[t]
        numerator = exp_u[first_good:first_good + mkt_size, :]
        denominator = 1 + numerator.sum(axis = 0)
        q[first_good:first_good + mkt_size, :] = numerator/denominator
        first_good += mkt_size
        
    # We assume each simulation carries the same weight
    # Then the predicted share is simply the average of individual shares
    s = np.matmul(q, np.repeat(1/N, N))  
        
    return [q,s]

III. Define the function that uses contraction mapping to find $\delta_{jt}$ given $s_{jt}$

In [8]:
# define a class so I can repeatedly update the delta value
class delta:
    def __init__(self, delta):
        self.delta = delta
        
# initialize a delta object using the delta_0 values
delta_0 = df.diff_2.values
d = delta(delta_0)

In [9]:
@jit
def solve_delta(s, x, v, p, y, delta, theta_2, J, T, N, tol):
    # define the initial tolerance value
    eps = 10
    
    # initialize delta
    delta_old = delta
    
    while eps > tol:
        # extract shares
        output = compute_share(x, v, p, y, delta_old, theta_2, J, T, N)
        s_hat = output[1]
        
        # contraction mapping
        delta_new = delta_old + np.log(s/s_hat)
        
        # update tolerance
        eps = np.max(np.abs(delta_new - delta_old))
        #print(eps)
        
        # update delta
        delta_old = delta_new.copy()
        
        return delta_old

IV. Define a function to compute marginal cost:

Recall that, $s_j\approx \frac{1}{NS}\sum_{i=1}^{NS}\frac{exp(\tilde u_{ij})}{1+\sum_{k=1}^{J}exp(\tilde u_{ik})}$, where $\tilde u_{ij} = \delta_{j} +  \sum_k\sigma_kx_{jk}v_{ik} -\alpha \frac{p_{j}}{y_i}$ is the indirect utility net of logit shock.

Then $\frac{\partial s_{j}}{\partial p_j} = \frac{1}{NS}\sum_{i=1}^{NS}\frac{\alpha}{y_i}(s_{ij}^2-s_{ij})$ and $\frac{\partial s_{j}}{\partial p_k} = \frac{1}{NS}\sum_{i=1}^{NS}\frac{\alpha}{y_i} s_{ij} s_{ik}$, where $s_{ij}$ is the individual share of consumer $i$ on product $j$.

Write in matrix form, we have

\begin{align*}
\Omega \approx \frac{1}{NS}\sum_{i=1}^{NS}\frac{\alpha}{y_i}\cdot \mathcal H \cdot (s_i s_i'-diag(s_i)) 
\end{align*}

where $\mathcal H$ is the ownership matrix, and $s_i$ is the indivual share of simulated consumer $i$.

After obtaining $\Omega$, we can compute marginal cost by:
\begin{align*}
mc = p-b = p - \Omega^{-1}s
\end{align*}

In [10]:
@jit
def compute_mc(q_s, firms, p, y, alpha, J, T, N, unique_mkts, markets):
    
    # predefine output vector
    marginal_cost = np.zeros(np.sum(J))
    
    # make sure the value of alpha is positive
    alpha = np.abs(alpha)
    
    # individual shares
    q = q_s[0]
    
    # predicted shares
    s = q_s[1].reshape((-1,1))
    
    # reshape the price vector
    p = p.reshape((-1,1))
    
    # iterate over markets
    for m in unique_mkts:
        # obtain list of firms operating in that market/year
        firm_yr = firms[markets == m]
        
        # obtain list of prices of goods in that market/year
        price = p[markets == m]
        
        # J_t x J_t block matrix of 1's indicating goods belonging to same firm in that market/year
        # also known as the ownership matrix
        ownership = np.equal(firm_yr, np.transpose(firm_yr))
        
        # obtain matrix of individual shares for all simulations and all goods in that market/year
        q_m = q[markets == m,:]
        
        # number of products in that market
        no_of_products = np.size(q_m,0)
        
        # predefine the Omega matrix (cross-price derivative matrix w.r.t. ownership matrix)
        gradient = np.zeros((no_of_products, no_of_products))
        
        for i in range(N):
            q_mi = q_m[:,i].reshape((-1,1))
            gradient += (1/N) * alpha/y[i, m-1] * ownership * (q_mi @ q_mi.T - np.diag(q_m[:,i]))
        
        
        b = np.linalg.inv(-gradient)@s[markets == m]
        mc = price - b
        mc[mc < 0] = 0.001
        
        marginal_cost[markets == m] = mc.flatten()
        
        
    return marginal_cost

V. Define a function to generate instruments used by BLP(1995):

The instrument has two parts:

total_firms contains a vector of all summed product/cost characteristics produced by the same firm.

total_mkts contains a vector of all summed product/cost characteristics produced by all firms in the market.

In [11]:
def generate_iv(char, firms, unique_mkts, markets):
    # predefine demand and supply sides instruments
    total_mkts = np.zeros((np.size(char, axis = 0), np.size(char, axis = 1)))
    total_firms = np.zeros((np.size(char, axis = 0), np.size(char, axis = 1)))
    
    for m in unique_mkts:
        sub = char[markets == m, :]
        firm_info = firms[markets == m]
        ownership = np.equal(firm_info, np.transpose(firm_info))
        
        z_1 = np.zeros((np.size(sub, axis = 0), np.size(sub, axis = 1)))
        z_2 = np.zeros((np.size(sub, axis = 0), np.size(sub, axis = 1)))
        
        for i in range(np.size(sub, axis = 1)):
            z_1[:,i] = (sub[:,i].reshape((-1,1)) * ownership).T.sum(axis=0)
            
        total_firms[markets == m, :] = z_1
        
        for i in range(np.size(sub, axis = 1)):
            z_2[:,i] = (sub[:,i].reshape((-1,1)) * (ownership + np.logical_not(ownership))).sum(axis=0)
            
        total_mkts[markets == m, :] = z_2
        
    return [total_firms, total_mkts]

VI: Define objective function that can search over nonlinear parameters $\theta_2$:

Step 1: Given non-linear paramerters $\theta_2$, actual market share $s$, solve the optimal $\hat\delta$

Step 2: Compute log marginal cost $log(mc)$. 

Step 3: Stack $\mathbf y = (\hat\delta', log(mc)')'$, $X = (X_d', X_s')'$, $Z = (Z_d', Z_s')'$.

Step 4: Obtain the linear paramter $\hat\theta_1 = (X'ZWZ'X)^{-1}X'ZWZ'Y$ by GMM:

  Note that we have $\mathbb E[z_i(y_i-x_i'\theta_1)] = 0$
  
  Then we have the sample analog $\frac{1}{N}Z'Y-\frac{1}{N}Z'X\theta_1 = 0$. However, since $d_z>d_{\theta_1}$, this is a over-identified linear system, the equality cannot hold. We can estimate $\theta_1$ using GLS (Generalized Least Squares):
  
  Denote $\eta = Z'Y$, $G = Z'X$, the previous equation can be written as $\eta = G\theta_1 + u$. The estimates of $\theta_1$ is $\hat\theta_1 = (G'WG)^{-1}G'W\eta$, which is equivalent to $\hat\theta_1 = (X'ZWZ'X)^{-1}X'ZWZ'Y$

Step 5: obtain the residual $\hat\xi = \mathbf y - X\hat\theta_1$

Step 6: $\theta_2 = \text{argmin}_{\theta\in\Theta}\hat\xi'Z W Z'\hat\xi$ using $\mathbb E[Z'\xi] = 0$

In [12]:
def obj_fcn(theta_2, s, X_d, V, p, y, J, T, N, unique_mkts, markets, tol, 
              Z_d, Z_s, X_s, w, firms):
    
    obs = np.sum(J)
    
    # find the converged delta value
    d.delta = solve_delta(s, X_d, V, p, y, d.delta, theta_2, J, T, N, tol)
    
    # obtain individual shares and actual shares from delta
    q_s = compute_share(X_d, V, p, y, d.delta, theta_2, J, T, N)
    
    # compute marginal costs
    mc = compute_mc(q_s, firms, p, y, theta_2[5], J, T, N, unique_mkts, markets).reshape((-1,1))

    # stack both demand and supply side variables
    y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))

    # create characteristics matrix that includes both supply and demand side
    # with demand characteristics on the top left and supply on the bottom right
    x = scipy.linalg.block_diag(X_d,X_s)

    # create matrix of supply and demand instruments, again with
    #  demand instruments on the right and supply on the left (top/down changed)
    z = scipy.linalg.block_diag(Z_d,Z_s)

    # get linear parameters
    theta_1 = np.linalg.inv(x.T @ z @ w @ z.T @ x) @ (x.T @ z @ w @ z.T @ y2)

    # get the error term xi
    xi_w = y2 - x @ theta_1

    # compute g_bar in GMM
    g = z.T @ xi_w

    obj = float(g.T @ w @ g)
    
    #print([theta_2, obj])
    
    return obj

### 4. Replications

#### Table I: Descriptive Statistics

In [13]:
# create table
table_1 = pd.DataFrame()

# calculate weighted means of the following column with quantity weights
table_1[["Price", "Domestic", "Japan", "European", "HP/Wt", "Size", "Air", "MPG", "MP$", "drop"]] = \
df[["price", "domestic", "japan", "european", "hpwt", "space", "air", "mpg", "mpd", "quantity"]] \
    .groupby(df.year).apply(lambda x: pd.Series(np.average(x, weights=x["quantity"], axis = 0)))

# count number of models per year/market
table_1.insert(0, "No. of Models", df.groupby("year").sum().cons.values)

# mean quantity per year/market
table_1.insert(1, "Quantity", df.quantity.groupby(df.year).mean()) 

# delete the extraneous weighted quantity column
table_1.drop('drop', axis=1, inplace=True)
np.round(table_1, 3)

No. of Models  Quantity   Price  Domestic  Japan  European  HP/Wt  \
year                                                                      
71               92    86.892   7.868     0.866  0.057     0.077  0.490   
72               89    98.623   7.979     0.892  0.042     0.066  0.391   
73               86    92.785   7.535     0.932  0.040     0.028  0.364   
74               72   105.119   7.506     0.887  0.050     0.064  0.347   
75               93    84.775   7.821     0.853  0.083     0.064  0.337   
76               99    93.382   7.787     0.876  0.081     0.043  0.338   
77               95    97.727   7.651     0.837  0.112     0.051  0.340   
78               95    99.444   7.645     0.855  0.107     0.039  0.346   
79              102    82.742   7.599     0.803  0.158     0.038  0.348   
80              103    71.567   7.718     0.773  0.191     0.036  0.350   
81              116    62.030   8.349     0.741  0.213     0.046  0.349   
82              110    61.893   8.831     0.714  0.235     0.051  0.347   
83              115    67.878   8.821     0.734  0.215     0.051  0.351   
84              113    85.933   8.870     0.783  0.179     0.038  0.361   
85              136    78.143   8.938     0.761  0.191     0.048  0.372   
86              130    83.756   9.382     0.733  0.216     0.050  0.379   
87              143    67.667   9.965     0.702  0.245     0.052  0.395   
88              150    67.078  10.069     0.717  0.237     0.045  0.396   
89              147    62.914  10.321     0.690  0.261     0.049  0.406   
90              131    66.377  10.337     0.682  0.276     0.043  0.419   

       Size    Air    MPG    MP$  
year                              
71    1.496  0.000  1.662  1.849  
72    1.510  0.014  1.619  1.875  
73    1.529  0.022  1.589  1.818  
74    1.510  0.026  1.567  1.452  
75    1.479  0.054  1.584  1.503  
76    1.508  0.059  1.759  1.696  
77    1.467  0.032  1.947  1.835  
78    1.405  0.034  1.982  1.929  
79    1.343  0.047  2.061  1.657  
80    1.296  0.078  2.215  1.466  
81    1.286  0.094  2.363  1.559  
82    1.277  0.134  2.440  1.817  
83    1.276  0.126  2.601  2.087  
84    1.293  0.129  2.469  2.117  
85    1.265  0.140  2.261  2.024  
86    1.249  0.176  2.416  2.856  
87    1.246  0.229  2.327  2.789  
88    1.251  0.237  2.334  2.919  
89    1.259  0.289  2.310  2.806  
90    1.270  0.308  2.270  2.852

#### Table III: Results with Logit Demand and Marginal Cost Pricing

1. The first column shows the result of the OLS logit demand:
\begin{align}
ln(s_j)-ln(s_0) = -\alpha p_j + x_j'\beta + \xi_j
\end{align}

In [14]:
table3_column1 = LinearRegression().fit(df[["hpwt", "air", "mpd", "space", "price"]], df.diff_2)
np.hstack((table3_column1.intercept_, table3_column1.coef_))

array([-10.07300751,  -0.12309488,  -0.03441478,   0.26546568,
         2.34191416,  -0.08860627])

2. The second column shows the result of IV logit demand: (we use 2-step GMM for estimation)

In [15]:
# generate IV for demand and supply sides
tempDemand = generate_iv(X_d, firms, unique_mkts, markets)
tempSupply = generate_iv(X_s, firms, unique_mkts, markets)

# generate demand IV matrix Z
Z_d = np.hstack((X_d, tempDemand[0], tempDemand[1]))

# generate supply IV matrix Z
Z_s = np.hstack((X_s, tempSupply[0], tempSupply[1], df.mpd.values.reshape((-1,1))))

# generate full characteristic matrix X by including price
X_base = np.hstack((X_d, p.reshape((-1,1))))

# define matrices
ZX = Z_d.T @ X_base
ZDelta = Z_d.T @ delta_0

# 1st-step GMM using identity weighting matrix
first_beta = np.linalg.inv(ZX.T @ ZX) @ ZX.T @ ZDelta

# obtain the residual
e = delta_0 - X_base @ first_beta

# calculate the optimal weighting matrix
# which is the inverse of the variance of the moment function
moment = e.reshape((-1,1)) * Z_d

demean = moment - moment.mean(axis=0).reshape((1,-1))

cov = demean.T @ demean / demean.shape[0]

W_iv = np.linalg.inv(cov)

# 2nd-step GMM using the optimal weighting matrix
table3_column2 = np.linalg.inv(ZX.T @ W_iv @ ZX) @ ZX.T @ W_iv @ ZDelta

table3_column2

array([-9.27629294,  1.94935115,  1.28739148,  0.05456147,  2.35760254,
       -0.21578695])

3. The third column shows the result of OLS ln(price) on $w$:
\begin{align}
ln(p) = w'\gamma + \omega
\end{align}

In [16]:
table3_column3 = LinearRegression().fit(
    df[["ln_hpwt", "air", "ln_mpg", "ln_space", "trend"]], df.ln_price)

np.hstack((table3_column3.intercept_, table3_column3.coef_))

array([ 1.88192125,  0.52033668,  0.6797513 , -0.47064027,  0.12482708,
        0.01283075])

#### Table IV: Esimated Parameters of the Demand and Pricing Equations (column 3)

In [17]:
# stack IV matrice for demand and supply
Z = scipy.linalg.block_diag(Z_d, Z_s)

# initial weighting matrix suggested by Aviv Nevo's appendix
W_init = np.linalg.inv(Z.T @ Z)

In [18]:
# test if the objective function works given a set of non-linear starting parameters
# this starting parameter is from BLP(1995)
theta_2 = [3.612, 4.628, 1.818, 1.050, 2.056, 43.501]

t0 = time.time()

obj = obj_fcn(theta_2, df.share.values, 
              X_d, V, p, y_it, J, T, N, unique_mkts, markets, 1e-5,
             Z_d, Z_s, X_s, W_init, firms)

time.time() - t0

6.666961193084717

In [19]:
# 1st-step GMM estimation:
# search over parameters that minimize the objective function using initial weighting matrix

t1 = time.time()

# set bounds for parameter space
bds = ((0,np.inf), (0,np.inf), (0,np.inf), 
        (0,np.inf), (0,np.inf), (5,np.inf))

first_step_est = minimize(obj_fcn,
                          theta_2, 
                          args = (df.share.values, X_d, V, p, y_it, 
                                  J, T, N, unique_mkts, markets, 1e-4, 
                                  Z_d, Z_s, X_s, W_init, firms), 
                          bounds = bds,
                          method = "L-BFGS-B",
                          options = {'maxiter': 1000, 'maxfun': 1000, 'eps': 1e-3},
                          tol = 1e-4)

time.time() - t1

148.18846082687378

In [20]:
# Saving
outfile = open("first_step_est_bfgs.pickle", "wb")
pickle.dump(first_step_est, outfile)
outfile.close()

# Reading
with open("first_step_est_bfgs.pickle", "rb") as infile:
    first_step_est = pickle.load(infile)

In [21]:
# calculate the (feasible) optimal weighting matrix
first_theta_2 = first_step_est.x

# calculate mean utility given the optimal parameters
d.delta = solve_delta(df.share.values, X_d, V, p, y_it,
                         d.delta, first_theta_2, J, T, N, 1e-5)

# calculate probabilities and shares given the optimal theta_2
q_s = compute_share(X_d, V, p, y_it, d.delta, first_theta_2, J, T, N)

# calculate marginal costs
mc = compute_mc(q_s, firms, p, y_it, first_theta_2[5], J, T, N, unique_mkts, markets).reshape((-1,1))

# stack matrices for regression
y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))
X = scipy.linalg.block_diag(X_d,X_s)
Z = scipy.linalg.block_diag(Z_d,Z_s)

# obtain the error
first_theta_1 = np.linalg.inv(X.T @ Z @ W_init @ Z.T @ X) @ (X.T @ Z @ W_init @ Z.T @ y2)
xi_w = y2 - X @ first_theta_1

# calculate weighting matrix
moment_blp = Z * xi_w
cov_blp = moment_blp.T @ moment_blp / np.sum(J)

optimal_weight = scipy.linalg.inv(cov_blp)

In [22]:
# now search for optimal parameters with the optimal weighting matrix
t2 = time.time()

second_step_est = minimize(obj_fcn,
                          theta_2, 
                          args = (df.share.values, X_d, V, p, y_it, 
                                  J, T, N, unique_mkts, markets, 1e-4, 
                                  Z_d, Z_s, X_s, optimal_weight, firms), 
                          bounds = bds,
                          method = "L-BFGS-B",
                          options = {'maxiter': 1000, 'maxfun': 1000, 'eps': 1e-3},
                          tol = 1e-4)

time.time() - t2

90.58367586135864

In [23]:
# Saving
outfile = open("second_step_est.pickle", "wb")
pickle.dump(second_step_est, outfile)
outfile.close()

# Reading
with open("second_step_est.pickle", "rb") as infile:
    second_step_est = pickle.load(infile)

1. Non-linear parameter estimates: Std. Deviations ($\sigma_\beta$'s)

In [24]:
second_theta_2 = second_step_est.x
second_theta_2

array([ 4.6119995 ,  4.6278806 ,  1.8179531 ,  1.04997291,  2.05594696,
       43.5000067 ])

2. Linear parameters:

First 5 are the demand side means (Constant, HP/Weight, Air, MP$, Size)

Last 6 are the cost side params (Constant, ln(HP/Weight), Air, ln(MPG), ln(Size), Trend)

In [25]:
d.delta = solve_delta(df.share.values, X_d, V, p, y_it, d.delta, second_theta_2,
                        J, T, N, 1e-4)
q_s = compute_share(X_d, V, p, y_it, d.delta, second_theta_2, J, T, N)

mc = compute_mc(q_s, firms, p, y_it, second_theta_2[5], J, T, N, unique_mkts, markets).reshape((-1,1))

y2 = np.vstack((d.delta.reshape((-1,1)), np.log(mc)))

second_theta_1 = np.linalg.inv(X.T @ Z @ optimal_weight @ Z.T @ X) @ (X.T @ Z @ optimal_weight @ Z.T @ y2)
second_theta_1

array([[-7.49341121],
       [ 2.67870538],
       [ 0.68947476],
       [ 0.07518924],
       [ 3.97380871],
       [ 1.32364628],
       [ 0.50838294],
       [ 0.59417088],
       [-0.34508292],
       [-0.07242206],
       [ 0.01432692]])

In [26]:
# average markup (compare to table 12 of Conlon and Gortmaker (2019))
np.mean((p.flatten() - mc.flatten()) / p.flatten())

0.30665511092130693

#### Table VI: Own- and Cross-Price Semi-Elasticities:

(the change of percentage market share given the  \$1k price change)

$\epsilon_{ij} = \frac{\partial s_i}{\partial p_j} \cdot \frac{100}{s_i}$

In [27]:
# We first compute the Omega matrix (gradient w.r.t. price) using estimates from 2-step GMM
# math derivation see above function compute_mc()

share_deriv = []
q = q_s[0]
s = q_s[1]

for m in unique_mkts:
    # list of firms in that market/year
    firm_yr = firms[markets == m]
    
    # list of prices in that market/year
    price = p[markets == m]
    
    # ownership matrix
    ownership = np.equal(firm_yr, np.transpose(firm_yr))
    
    # individual shares (or individual quantities) for all products in that market/year
    q_m = q[markets == m, :]
    
    # number of products in that market
    no_of_products = np.size(q_m, 0)
    
    # predefine the omega matrix       
    deriv_m = np.zeros((no_of_products, no_of_products))
    
    # calculate omega matrix
    for i in range(N):
        q_mi = q_m[:, i].reshape((-1,1))
        deriv_m += second_theta_2[5] / y_it[i, m - 1] * 1/N * (q_mi @ q_mi.T - np.diag(q_m[:,i]))
        
    share_deriv.append(deriv_m)

In [28]:
# for example, we obtain the own-price derivative for Mazda323 in 1990
mz323_deriv = (share_deriv[19][df.modelvec[markets == 20] == "MZ323"]).flatten()[df.modelvec[markets == 20] == "MZ323"]
mz323_deriv

array([-0.00030612])

In [29]:
# or for BMW735i in 1990
bw735i_deriv = (share_deriv[19][df.modelvec[markets == 20] == "BW735i"]).flatten()[df.modelvec[markets == 20] == "BW735i"]
bw735i_deriv

array([-6.38248361e-06])

In [30]:
# obtain the Mazda323 mkt share in 1990
mz323_s = s[(markets == 20) & (df.modelvec == "MZ323")]

# obtain the BMW735i market share in 1990
bw735i_s = s[(markets == 20) & (df.modelvec == "BW735i")]

In [31]:
# compare with table VI, first row first column of BLP (1995)
mz323_deriv/ mz323_s * 100

array([-125.36914283])

In [32]:
# now we create all of table VI

# extract all of the cars
table_vi_cars = ["MZ323", "NISENT", "FDESCO", "CVCAVA", "HDACCO", "FDTAUR", "BKCENT",
                "NIMAXI", "ACLEGE", "LNTOWN", "CDSEVI", "LXLS40", "BW735i"]

# obtain share derivs and shares relevant cars in 1990
deriv_1990 = share_deriv[19]
s_1990 = s[markets == 20]

# initialize the matrix dimensions of table VI
table_vi = np.zeros((len(table_vi_cars), len(table_vi_cars)))

# iterate across cars to obtain table VI
row = 0
for car1 in table_vi_cars:
    col = 0
    for car2 in table_vi_cars:
        table_vi[row, col] = (deriv_1990[df.modelvec[markets == 20] == car1].flatten()[df.modelvec[markets == 20] == car2] /\
                             s_1990[df.modelvec[markets == 20] == car2] *100)
        col += 1
    row += 1

In [33]:
# store in dataframe for easier viewing
table_vi = pd.DataFrame(np.round(table_vi, 3))

# renaming rows and columns
table_vi.index = table_vi_cars
table_vi.columns = table_vi_cars

table_vi

MZ323   NISENT  FDESCO   CVCAVA  HDACCO  FDTAUR  BKCENT  NIMAXI  \
MZ323  -125.369    0.900   0.959    0.803   0.115   0.052   0.059   0.011   
NISENT    1.936 -107.754   1.625    1.393   0.295   0.135   0.147   0.036   
FDESCO   12.031    9.475 -98.553    7.843   1.650   0.644   0.766   0.180   
CVCAVA   10.299    8.302   8.017 -101.361   1.926   1.104   0.977   0.264   
HDACCO    2.085    2.488   2.384    2.723 -47.253   1.953   1.530   0.988   
FDTAUR    0.706    0.852   0.699    1.172   1.467 -40.411   1.057   0.651   
BKCENT    0.285    0.333   0.298    0.372   0.411   0.378 -42.275   0.757   
NIMAXI    0.049    0.072   0.062    0.090   0.237   0.208   0.675 -27.509   
ACLEGE    0.007    0.011   0.010    0.013   0.059   0.063   0.156   0.221   
LNTOWN    0.008    0.014   0.012    0.019   0.101   0.195   0.336   0.443   
CDSEVI    0.001    0.002   0.002    0.003   0.019   0.028   0.048   0.091   
LXLS40    0.002    0.003   0.003    0.003   0.022   0.021   0.049   0.108   
BW735i    0.000    0.000   0.000    0.000   0.002   0.003   0.006   0.014   

        ACLEGE  LNTOWN  CDSEVI  LXLS40  BW735i  
MZ323    0.003   0.001   0.001   0.001   0.000  
NISENT   0.010   0.005   0.003   0.004   0.001  
FDESCO   0.055   0.024   0.017   0.021   0.004  
CVCAVA   0.070   0.038   0.026   0.023   0.007  
HDACCO   0.459   0.282   0.234   0.228   0.078  
FDTAUR   0.369   0.411   0.263   0.161   0.103  
BKCENT   0.326   0.253   0.164   0.135   0.059  
NIMAXI   0.413   0.298   0.275   0.264   0.135  
ACLEGE -15.244   0.184   0.196   0.197   0.137  
LNTOWN   0.509 -13.311   0.528   0.422   0.334  
CDSEVI   0.121   0.118 -10.714   0.129   0.115  
LXLS40   0.151   0.117   0.160  -9.024   0.158  
BW735i   0.027   0.023   0.036   0.040  -5.744

### Citations

Berry, S., Levinsohn, J., & Pakes, A. (1995). Automobile prices in market equilibrium. Econometrica: Journal of the Econometric Society, 841-890.

Nevo, A. (2000). A practitioner's guide to estimation of random‐coefficients logit models of demand. Journal of economics & management strategy, 9(4), 513-548.

Ivan Li's website: Replication of the classic BLP (1995). Retrieved June, 2023, from https://www.ivan-li.com/code/blp_1995